name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Format.
        run: make format
      - name: Linting & vetting.
        run: make lint

  Testing_and_building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all tags as well.
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Running tests
        run: make test
        env:
          VIXEOD_KEY: ${{ secrets.VIXEOD_KEY }}

      - name: Check generated files # Ensure generated files are up to date.
        run: make generate-check
        
      - name: Building
        run: make build
